export const ROUTER = {
    welcome: "welcome",
    authentication: "authentication",
    projects: "projects",
    projectDetails: "project-details",
    projectManager: "project-manager",
    projectManagerEdit: "project-manager-edit",
    synergies: "synergies",
    investment: "investment",
    profile: "profile",
    karma: "karma",
    chat: "chat",
    synergyRequests: "synergy-requests",
    synergiesManager: "synergies-manager",
    myContent: "my-content",
    ambassadorProjects: "ambassador-projects",
    SocietyFullList: 'society-full-list',
    error404: '404',
    error405: '405'
};